site_name: HIS4936 Final Project Starter
theme_dir: theme
theme: null
copyright: 'Copyright &copy; 2017 <a href="mailto:ccroson@mail.usf.edu">Curtis Croson</a>'
repo_url: https://github.com/thePortus/his4936-starter/
repo_name: 'GitHub'
pages:
- Home: 'index.md'
- POW Project: 'POW_project_starter.md'
- Credits: 'credits.md'
